name: "Sbrubbles"
title: "Humberto's personal site"
description: "My personal site."
url: "https://sbrubbles.org"
baseurl: ""
author: "Humberto Anjos"
profile_image: assets/images/profile.jpg
email: h.anjos@sbrubbles.org

permalink: pretty
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Humberto Anjos"
      license: "cc-by"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Humberto Anjos"
      license: "cc-by"
      image: "assets/images/profile.jpg"

include: [ "/.well-known" ]

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
