name: "Sbrubbles"
description: "My personal site."
url: https://sbrubbles.org
author: "Humberto Anjos"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Humberto Anjos"
      license: "cc-by"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "Humberto Anjos"
      license: "cc-by"
      image: "assets/images/profile.jpg"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
