name: Sbrubbles
description: My personal site.
url: https://sbrubbles.org
author: Humberto Anjos

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      license: "cc-by"
  - scope:
      path: ""
    values:
      layout: "default"
      license: "cc-by"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
